### PR TITLE
fix(server/vehicle): use correct export for vehicle getters and add missing TS export

### LINKED ISSUE #5: GetVehicle does not return a OxVehicle.
I have built a garage script that has been working with no problems for quite some time now. However, since commit 08c7c89d71323312521d319280001467ac844039 it seems like the function `GetVehicle` does not return an OxVehicle anymore. I suspect this is because of [this](https://github.com/CommunityOx/ox_core/commit/08c7c89d71323312521d319280001467ac844039#diff-d45c279ec2521e30fec966921981244f86dc13d3a05975a9ad026d193f8eb8a2R65-R67) code snippet, which should make sense.

Additionally, in my opinion, the above snippet is a bit useless, because there already is `GetVehicleFromVin`, which works well in my case in the context of a vehicle key system. Anyway, coming back to the original problem, below is the code snippet that doesn't work.

```ts
const entity = GetVehiclePedIsIn(GetPlayerPed(String(source)), false);
const vehicle = GetVehicle(entity);
```

If I were to console.log `vehicle`, I will get `{}`.
I have also tested the following approach, which produces the desireable result.

```ts
const entity = GetVehiclePedIsIn(GetPlayerPed(String(source)), false);
const vehicle = GetVehicleFromNetId(NetworkGetNetworkIdFromEntity(entity));
```

One extra thing I also did was to look at how the `dv` command works. It basically follows the same principle, but instead of using `GetVehicle`, it uses `OxVehicle.getFromEntity`, which, I think, confirms the suspicions that overloading the `GetVehicle` method is the cause of the issue.

If necessary, I can do more extensive research and come up with new reproduction code.

### PR DESCRIPTION
**Pull request by andreutu**
This PR aims to fix an oversight that mostly affects TypeScript users. Currently, the only way to get a vehicle using its entity ID in TypeScript is through `GetVehicle`. However, that function uses an export that does not exist, at least not anymore. 
In lua, users are able to use the function `Ox.GetVehicleFromEntity`, which works as it should. In TS, there is no function under that name.

This PR aims to fix this problem by adding the `GetVehicleFromEntity` function to TypeScript and using the correct exports in `GetVehicle` functions, which are only kept because, if they were removed, it would break a lot of scripts no matter the environment.

I am however going to need a say from maintainers on whether if it is a good idea to keep the GetVehicle function or remove the GetVehicleFromEntity function and keep the first one.

Fixes #5.

### CODE REVIEW

**Comment by antond15** [comment]
Thanks for the PR. The addition of `GetVehicleFromEntity` to TS is great.

However your change to `GetVehicle` is breaking.
`GetVehicle` should either take `vin` — or both `vin` and `entityId` and use the proper getter based on parameter type (`string|number` respectively).

`OxVehicle` can exist without being spawned - not having `entityId` assigned, therefore the default `Get` call should use `vin`.

**Comment by andreutu** [comment]
Okay, think I got it. I'll implement these changes now.

**Comment by andreutu** [comment]
Should be good to go 👍🏻

**Review by FjamZoo — DISMISSED** [review]

**Comment by FjamZoo** [comment]
will wait for @antond15 to double check before merging

File: lib/server/vehicle.ts [hunk 1]
```diff
@@ -64,7 +64,11 @@ function CreateVehicleInstance(vehicle: _OxVehicle) {
 
 export function GetVehicle(entityId: number): OxVehicle;
 export function GetVehicle(vin: number | string) {
-  return typeof vin === 'string' ? GetVehicleFromVin(vin) : CreateVehicleInstance(exports.ox_core.GetVehicle(vin));
+  return typeof vin === 'string' ? GetVehicleFromVin(vin) : GetVehicleFromEntity(vin);
+}
+
+export function GetVehicleFromEntity(entityId: number) {
+  CreateVehicleInstance(exports.ox_core.GetVehicleFromEntity(entityId));
```
Comment (antond15) [inline lib/server/vehicle.ts:71]: Missing a return

**Review by antond15 — CHANGES_REQUESTED** [review]

File: lib/server/vehicle.ts [hunk 2]
```diff
@@ -64,7 +64,11 @@ function CreateVehicleInstance(vehicle: _OxVehicle) {
 
 export function GetVehicle(entityId: number): OxVehicle;
```
Comment (antond15) [inline lib/server/vehicle.ts:65]: There is a missing overload for `vin`. The code below should do fine.

```ts
export function GetVehicle(entityId: number): OxVehicle;
export function GetVehicle(vin: string): OxVehicle;
export function GetVehicle(handle: number | string) {
  return typeof handle === 'string' ? GetVehicleFromVin(handle) : GetVehicleFromEntity(handle);
}
```

**Review by antond15 — CHANGES_REQUESTED** [review]

**Review by antond15 — APPROVED** [review]
LGTM

**Review by FjamZoo — APPROVED** [review]
